name: razgovorko
description: "Simple chat application written in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter

  fast_contacts: 4.0.0
  flutter_libphonenumber: 2.5.0
  get_it: 8.0.2
  logger: 2.4.0
  phone_numbers_parser: 9.0.3
  supabase_flutter: 2.8.0
  watch_it: 1.5.1

dev_dependencies:
  build_runner: 2.4.13
  envied_generator: 0.5.4+1
  flutter_launcher_icons: 0.14.1
  flutter_native_splash: 2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/Outfit-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/Outfit-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/Outfit-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Outfit-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Outfit-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Outfit-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Outfit-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Outfit-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Outfit-Black.ttf
  #         weight: 900

# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#FFFFFF'
    theme_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    color: '#FFFFFF'
    image_dark: 'assets/splash_icon.png'
    color_dark: '#2B2D42'
