name: razgovorko
description: "Simple chat application written in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  country_code_picker_plus: 0.0.9
  fast_contacts: 4.0.0
  flutter_animate: 4.5.2
  flutter_libphonenumber: 2.5.0
  get_it: 8.0.2
  image_picker: 1.1.2
  intl: 0.20.1
  logger: 2.4.0
  supabase_flutter: 2.8.0
  watch_it: 1.5.1

dev_dependencies:
  build_runner: 2.4.13
  envied_generator: 0.5.4+1
  flutter_launcher_icons: 0.14.1
  flutter_native_splash: 2.4.2

dependency_overrides:
  intl: 0.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: AguDisplay
      fonts:
        - asset: assets/fonts/AguDisplay/AguDisplay-Regular.ttf
          weight: 600

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Kanit/Kanit-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Kanit/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit/Kanit-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Kanit/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit/Kanit-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit/Kanit-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit/Kanit-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Kanit/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit/Kanit-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit/Kanit-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Kanit/Kanit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Kanit/Kanit-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Kanit/Kanit-Black.ttf
          weight: 900
        - asset: assets/fonts/Kanit/Kanit-BlackItalic.ttf
          weight: 900
          style: italic

# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#FFFFFF'
    theme_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    color: '#FFFFFF'
    image_dark: 'assets/splash_icon.png'
    color_dark: '#2B2D42'
